print("Enter the values of a,b,c,p,q and r.")
a=int(input())
b=int(input())
c=int(input())
p=int(input())
q=int(input())
r=int(input())
x=((r*b)-(c*q))/((a*q)-(p*b))
y=((r*a)-(c*p))/((b*p)-(q*a))
print("The point of intersection is :-\t(",x,",",y,")")
